version: '3'
services:
  postgres:
    image: 'postgres:16'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'