server:
  servlet:
    context-path: /api

spring:
  application:
    name: 'spring-aop'

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver